name: Generate SDKs using liblab

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'liblab.config.json'
      - 'spec.json'
      - 'hooks/**'

jobs:
  build-and-pr:
    name: Generate SDKs and create PRs
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets are set
        run: |
          if [[ -n "${{ secrets.LIBLAB_TOKEN }}" && -n "${{ secrets.LIBLAB_GITHUB_TOKEN }}" ]]; then
            echo "Secrets are set, proceeding with the workflow"
          else
            echo "Error: Secrets not set, skipping the workflow"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install liblab
        run: npm install -g liblab

      - name: Start Build
        run: liblab build --yes

      - name: Create PRs to GitHub repos
        run: liblab pr
