name: Latest Liblab updates

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check-for-latest-liblab-updates:
    name: Generate SDKs and create PRs
    runs-on: ubuntu-latest
    env:
      LIBLAB_TOKEN: ${{ secrets.LIBLAB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.LIBLAB_GITHUB_TOKEN }}
      LIBLAB_ENVIRONMENT: development
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Build SDKs and publish PRs
        id: build_and_publish_prs
        uses: skosijer/gh-action@v1
        with:
          liblab_token: ${{ secrets.LIBLAB_TOKEN }}
          github_token: ${{ secrets.LIBLAB_GITHUB_TOKEN }}

      - name: Build status
        run: echo "Status is ${{ steps.build_and_publish_prs.outputs.status }}"



