name: Liblab SDK updates

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check-for-latest-liblab-updates:
    name: Generate SDKs and create PRs
    runs-on: ubuntu-latest
    env:
      LIBLAB_TOKEN: ${{ secrets.LIBLAB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.LIBLAB_GITHUB_TOKEN }}
      LIBLAB_ENVIRONMENT: development
    steps:
      - name: Stevan SDK updates
        uses: skosijer/gh-action/.github/workflows/ci.yml@v1.0.0
#        with:
#         liblab_token: ${{ secrets.LIBLAB_TOKEN }}
#         github_token: ${{ secrets.LIBLAB_GITHUB_TOKEN }}


